import {
  Home,
  Car,
  Wallet,
  GraduationCap,
  Leaf,
  Hammer,
  Building2,
  TrendingUp,
  Wrench,
  Factory,
  CreditCard,
  Truck,
  type LucideIcon,
} from 'lucide-react';

export interface LoanProduct {
  icon: LucideIcon;
  title: string;
  titleKey: string;
  description: string;
  descKey: string;
  amount: string;
  rate: string;
  duration: string;
  color: string;
  bgColor: string;
  features?: string[];
  featuresKey?: string;
}

export const getIndividualLoans = (t: any): LoanProduct[] => [
  {
    icon: Wallet,
    title: t.individualLoans?.personalLoan || 'Prêt Personnel',
    titleKey: 'personalLoan',
    description: t.individualLoans?.personalLoanDesc || 'Financement flexible pour tous vos projets personnels',
    descKey: 'personalLoanDesc',
    amount: '1 000€ - 75 000€',
    rate: '0,10% - 7%',
    duration: '12 - 84 mois',
    color: 'text-blue-600',
    bgColor: 'bg-blue-50 dark:bg-blue-950/20',
  },
  {
    icon: Home,
    title: t.individualLoans?.mortgageLoan || 'Prêt Immobilier',
    titleKey: 'mortgageLoan',
    description: t.individualLoans?.mortgageLoanDesc || "Financez l'achat de votre résidence principale ou secondaire",
    descKey: 'mortgageLoanDesc',
    amount: '50 000€ - 500 000€',
    rate: '2,5% - 4,5%',
    duration: '15 - 30 ans',
    color: 'text-green-600',
    bgColor: 'bg-green-50 dark:bg-green-950/20',
  },
  {
    icon: Car,
    title: t.individualLoans?.autoLoan || 'Crédit Auto',
    titleKey: 'autoLoan',
    description: t.individualLoans?.autoLoanDesc || "Achetez votre véhicule neuf ou d'occasion",
    descKey: 'autoLoanDesc',
    amount: '5 000€ - 75 000€',
    rate: '1,9% - 5,5%',
    duration: '24 - 84 mois',
    color: 'text-purple-600',
    bgColor: 'bg-purple-50 dark:bg-purple-950/20',
  },
  {
    icon: GraduationCap,
    title: t.individualLoans?.studentLoan || 'Prêt Étudiant',
    titleKey: 'studentLoan',
    description: t.individualLoans?.studentLoanDesc || 'Financez vos études avec des conditions avantageuses',
    descKey: 'studentLoanDesc',
    amount: '1 000€ - 50 000€',
    rate: '0,9% - 3,5%',
    duration: '24 - 120 mois',
    color: 'text-orange-600',
    bgColor: 'bg-orange-50 dark:bg-orange-950/20',
  },
  {
    icon: Leaf,
    title: t.individualLoans?.greenLoan || 'Prêt Vert',
    titleKey: 'greenLoan',
    description: t.individualLoans?.greenLoanDesc || 'Financez vos projets de rénovation énergétique',
    descKey: 'greenLoanDesc',
    amount: '3 000€ - 75 000€',
    rate: '0,5% - 4,0%',
    duration: '12 - 180 mois',
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-50 dark:bg-emerald-950/20',
  },
  {
    icon: Hammer,
    title: t.individualLoans?.renovationLoan || 'Prêt Travaux',
    titleKey: 'renovationLoan',
    description: t.individualLoans?.renovationLoanDesc || 'Rénovez votre logement avec un financement adapté',
    descKey: 'renovationLoanDesc',
    amount: '1 500€ - 75 000€',
    rate: '2,5% - 6,9%',
    duration: '12 - 120 mois',
    color: 'text-pink-600',
    bgColor: 'bg-pink-50 dark:bg-pink-950/20',
  },
];

export const getBusinessLoans = (t: any): LoanProduct[] => [
  {
    icon: Building2,
    title: t.businessLoans?.businessLoan || 'Prêt Professionnel',
    titleKey: 'businessLoan',
    description: t.businessLoans?.businessLoanDesc || 'Développez votre activité professionnelle',
    descKey: 'businessLoanDesc',
    amount: '10 000€ - 500 000€',
    rate: '3,5% - 8,5%',
    duration: '12 - 84 mois',
    color: 'text-blue-600',
    bgColor: 'bg-blue-50 dark:bg-blue-950/20',
    featuresKey: 'businessLoanFeatures',
  },
  {
    icon: TrendingUp,
    title: t.businessLoans?.cashFlowCredit || 'Crédit de Trésorerie',
    titleKey: 'cashFlowCredit',
    description: t.businessLoans?.cashFlowCreditDesc || 'Gérez vos besoins de trésorerie au quotidien',
    descKey: 'cashFlowCreditDesc',
    amount: '5 000€ - 150 000€',
    rate: '4,0% - 9,0%',
    duration: '3 - 36 mois',
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-50 dark:bg-emerald-950/20',
    featuresKey: 'cashFlowCreditFeatures',
  },
  {
    icon: Wrench,
    title: t.businessLoans?.equipmentFinancing || 'Financement Équipement',
    titleKey: 'equipmentFinancing',
    description: t.businessLoans?.equipmentFinancingDesc || 'Équipez votre entreprise avec du matériel professionnel',
    descKey: 'equipmentFinancingDesc',
    amount: '20 000€ - 300 000€',
    rate: '3,9% - 7,5%',
    duration: '24 - 60 mois',
    color: 'text-orange-600',
    bgColor: 'bg-orange-50 dark:bg-orange-950/20',
    featuresKey: 'equipmentFinancingFeatures',
  },
  {
    icon: Factory,
    title: t.businessLoans?.commercialProperty || 'Immobilier Commercial',
    titleKey: 'commercialProperty',
    description: t.businessLoans?.commercialPropertyDesc || 'Acquérez vos locaux professionnels',
    descKey: 'commercialPropertyDesc',
    amount: '50 000€ - 2 000 000€',
    rate: '2,9% - 5,5%',
    duration: '5 - 25 ans',
    color: 'text-purple-600',
    bgColor: 'bg-purple-50 dark:bg-purple-950/20',
    featuresKey: 'commercialPropertyFeatures',
  },
  {
    icon: CreditCard,
    title: t.businessLoans?.lineOfCredit || 'Ligne de Crédit',
    titleKey: 'lineOfCredit',
    description: t.businessLoans?.lineOfCreditDesc || 'Accédez à une réserve de trésorerie renouvelable',
    descKey: 'lineOfCreditDesc',
    amount: '5 000€ - 100 000€',
    rate: '5,0% - 9,5%',
    duration: t.businessLoans?.lineOfCreditDuration || 'Renouvelable',
    color: 'text-cyan-600',
    bgColor: 'bg-cyan-50 dark:bg-cyan-950/20',
    featuresKey: 'lineOfCreditFeatures',
  },
  {
    icon: Truck,
    title: t.businessLoans?.vehicleFleet || 'Flotte de Véhicules',
    titleKey: 'vehicleFleet',
    description: t.businessLoans?.vehicleFleetDesc || 'Financez vos véhicules professionnels',
    descKey: 'vehicleFleetDesc',
    amount: '15 000€ - 250 000€',
    rate: '3,2% - 6,8%',
    duration: '24 - 60 mois',
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-50 dark:bg-indigo-950/20',
    featuresKey: 'vehicleFleetFeatures',
  },
];
